### ISSUE TITLE
bundle exec fastlane oss fails

### ISSUE THREAD

**Issue by lilredindy** [artsy/eidolon#688]
I am having a problem building with fastlane. 
i've attached colorized pdf output as well

~/Development/ios_apps/eidolon$ bundle exec fastlane oss
[✔] 🚀 
[16:20:47]: You have require'd a gem, if this is a third party gem, please use `fastlane_require 'yaml'` to ensure the gem is installed locally.
[16:20:47]: ----------------------------------------
[16:20:47]: --- Step: Verifying fastlane version ---
[16:20:47]: ----------------------------------------
[16:20:47]: Your fastlane version 2.85.0 matches the minimum requirement of 1.0.2  ✅
[16:20:47]: Driving the lane 'oss' 🚀
[16:20:47]: -------------------------------------
[16:20:47]: --- Step: Switch to oss_keys lane ---
[16:20:47]: -------------------------------------
[16:20:47]: Cruising over to lane 'oss_keys' 🚖
[16:20:47]: --------------------------------------------------------------------------------------------------------------------------------------------
[16:20:47]: Step: cd .. ; bundle exec pod keys set ArtsyAPIClientSecret '-' Eidolon ; bundle exec pod keys set ArtsyAPIClientKey '-' Eidolon ; bundle exec pod keys set HockeyProductionSecret '-' Eidolon ; bundle exec pod keys set HockeyBetaSecret '-' Eidolon ; bundle exec pod keys set SegmentWriteKey '-' Eidolon ; bundle exec pod keys set CardflightStagingAPIClientKey '-' Eidolon ; bundle exec pod keys set CardflightStagingMerchantAccountToken '-' Eidolon ; bundle exec pod keys set StripeStagingPublishableKey '-' Eidolon ; bundle exec pod keys set CardflightProductionAPIClientKey '-' Eidolon ; bundle exec pod keys set CardflightProductionMerchantAccountToken '-' Eidolon ; bundle exec pod keys set StripeProductionPublishableKey '-' Eidolon
[16:20:47]: --------------------------------------------------------------------------------------------------------------------------------------------
[16:20:47]: $ cd .. ; bundle exec pod keys set ArtsyAPIClientSecret '-' Eidolon ; bundle exec pod keys set ArtsyAPIClientKey '-' Eidolon ; bundle exec pod keys set HockeyProductionSecret '-' Eidolon ; bundle exec pod keys set HockeyBetaSecret '-' Eidolon ; bundle exec pod keys set SegmentWriteKey '-' Eidolon ; bundle exec pod keys set CardflightStagingAPIClientKey '-' Eidolon ; bundle exec pod keys set CardflightStagingMerchantAccountToken '-' Eidolon ; bundle exec pod keys set StripeStagingPublishableKey '-' Eidolon ; bundle exec pod keys set CardflightProductionAPIClientKey '-' Eidolon ; bundle exec pod keys set CardflightProductionMerchantAccountToken '-' Eidolon ; bundle exec pod keys set StripeProductionPublishableKey '-' Eidolon
[16:20:50]: ▸ Saved ArtsyAPIClientSecret to Eidolon.
[16:20:51]: ▸ Saved ArtsyAPIClientKey to Eidolon.
[16:20:53]: ▸ Saved HockeyProductionSecret to Eidolon.
[16:20:54]: ▸ Saved HockeyBetaSecret to Eidolon.
[16:20:56]: ▸ Saved SegmentWriteKey to Eidolon.
[16:20:57]: ▸ Saved CardflightStagingAPIClientKey to Eidolon.
[16:20:59]: ▸ Saved CardflightStagingMerchantAccountToken to Eidolon.
[16:21:00]: ▸ Saved StripeStagingPublishableKey to Eidolon.
[16:21:02]: ▸ Saved CardflightProductionAPIClientKey to Eidolon.
[16:21:03]: ▸ Saved CardflightProductionMerchantAccountToken to Eidolon.
[16:21:05]: ▸ Saved StripeProductionPublishableKey to Eidolon.
[16:21:05]: Cruising back to lane 'oss' 🚘
[16:21:05]: -----------------------
[16:21:05]: --- Step: cocoapods ---
[16:21:05]: -----------------------
[16:21:05]: $ bundle exec pod install
[16:21:08]: ▸ Analyzing dependencies
[16:21:08]: ▸ Pre-downloading: `DZNWebViewController` from `https://github.com/orta/DZNWebViewController.git`, commit `9121386901af95072fb19eaa3df7060ca46fc337`
[16:21:09]: ▸ Pre-downloading: `HockeySDK-Source` from `https://github.com/bitstadium/HockeySDK-iOS.git`, commit `e5c57e7509bc870bd08f2b93971bb2d6f22ab0b7`
[16:21:09]: ▸ Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
[16:21:10]: ▸ Pre-downloading: `UIImageViewAligned` from `https://github.com/ashfurrow/UIImageViewAligned.git`, commit `6f8cb5669b219ef08c90c2e2e5a082cadfe7565b`
[16:21:10]: ▸ [!] Unable to find a specification for `CardFlight-v4`
[16:21:10]: Exit status of command 'bundle exec pod install' was 1 instead of 0.
Analyzing dependencies
Pre-downloading: `DZNWebViewController` from `https://github.com/orta/DZNWebViewController.git`, commit `9121386901af95072fb19eaa3df7060ca46fc337`
Pre-downloading: `HockeySDK-Source` from `https://github.com/bitstadium/HockeySDK-iOS.git`, commit `e5c57e7509bc870bd08f2b93971bb2d6f22ab0b7`
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
Pre-downloading: `UIImageViewAligned` from `https://github.com/ashfurrow/UIImageViewAligned.git`, commit `6f8cb5669b219ef08c90c2e2e5a082cadfe7565b`
[!] Unable to find a specification for `CardFlight-v4`

+---------------+-----+
|    Lane Context     |
+---------------+-----+
| PLATFORM_NAME |     |
| LANE_NAME     | oss |
+---------------+-----+
[16:21:10]: Analyzing dependencies
Pre-downloading: `DZNWebViewController` from `https://github.com/orta/DZNWebViewController.git`, commit `9121386901af95072fb19eaa3df7060ca46fc337`
Pre-downloading: `HockeySDK-Source` from `https://github.com/bitstadium/HockeySDK-iOS.git`, commit `e5c57e7509bc870bd08f2b93971bb2d6f22ab0b7`
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
Pre-downloading: `UIImageViewAligned` from `https://github.com/ashfurrow/UIImageViewAligned.git`, commit `6f8cb5669b219ef08c90c2e2e5a082cadfe7565b`
[!] Unable to find a specification for `CardFlight-v4`

+------+-----------------------------------+-------------+
|                    fastlane summary                    |
+------+-----------------------------------+-------------+
| Step | Action                            | Time (in s) |
+------+-----------------------------------+-------------+
| 1    | Verifying fastlane version        | 0           |
| 2    | Switch to oss_keys lane           | 0           |
| 3    | cd .. ; bundle exec pod keys set  | 17          |
|      | ArtsyAPIClientSecret '-' Eid      |             |
| 💥   | cocoapods                         | 5           |
+------+-----------------------------------+-------------+

[16:21:10]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `shell_error!': [!] Analyzing dependencies (FastlaneCore::Interface::FastlaneShellError)
Pre-downloading: `DZNWebViewController` from `https://github.com/orta/DZNWebViewController.git`, commit `9121386901af95072fb19eaa3df7060ca46fc337`
Pre-downloading: `HockeySDK-Source` from `https://github.com/bitstadium/HockeySDK-iOS.git`, commit `e5c57e7509bc870bd08f2b93971bb2d6f22ab0b7`
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
Pre-downloading: `UIImageViewAligned` from `https://github.com/ashfurrow/UIImageViewAligned.git`, commit `6f8cb5669b219ef08c90c2e2e5a082cadfe7565b`
[!] Unable to find a specification for `CardFlight-v4`

	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/actions/cocoapods.rb:45:in `call_error_callback'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/actions/cocoapods.rb:34:in `block in run'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/helper/sh_helper.rb:78:in `sh_control_output'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/actions/cocoapods.rb:27:in `run'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:40:in `block in parsing_binding'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/lane_manager.rb:57:in `cruise_lane'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/gems/fastlane-2.85.0/bin/fastlane:20:in `<top (required)>'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/bin/fastlane:23:in `load'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/bin/fastlane:23:in `<main>'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/shriamin/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
[errors.pdf](https://github.com/artsy/eidolon/files/1804497/errors.pdf)

**Comment by orta** [comment]
looks like you need to do a `pod repo update` first

**Comment by lilredindy** [comment]
fix is to issue 'pod repo update' or perhaps 'pod repo update artsy' or perhaps prefix either with 'bundle exec ...'

**Comment by ashfurrow** [comment]
I'll add that to our `rake oss` command.

**Comment by lilredindy** [comment]
that took a long time, not sure if you need to update the master repo as well...maybe just 'pod repo update artsy' or 'bundle exec pod repo update artsy'...hope that helps

**Comment by boredomdenied** [comment]
actually this breaks fresh installs. I had to comment out 4 lines in fasttrack to get the initial `bundle exec fastlane oss` to work, then uncommented them and ran a second time for update artsy to hit.
